spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/manishi_dev
    username: root
    password: pass@123

  sql:
    init:
      mode: always

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
